"""
BIZIT Organism API Router
==========================
Exposes the Organism's live activity feed and control surface
to the frontend dashboard.
"""

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from routers.auth import get_current_user
from database.models import User
from sqlalchemy import func, desc
from database.database import get_db
from database.models import OrganismActivity, OrganismAlert, Business
from organism.scheduler import get_scheduler_status, start_organism, stop_organism
import time

router = APIRouter()


@router.get("/status")
def organism_status():
    """Current Organism scheduler status and job schedule."""
    status = get_scheduler_status()
    return {
        "organism": "BIZIT Autonomous Organism v1.0",
        "state": "ALIVE" if status["running"] else "DORMANT",
        **status,
    }


@router.get("/activity")
def get_activity(limit: int = 50, cycle: str = None, db: Session = Depends(get_db)):
    """
    Live activity feed — everything the Organism has done autonomously.
    Sorted newest first.
    """
    query = db.query(OrganismActivity).order_by(desc(OrganismActivity.timestamp))
    if cycle:
        query = query.filter(OrganismActivity.cycle == cycle.upper())
    activities = query.limit(limit).all()

    return {
        "count": len(activities),
        "activities": [
            {
                "id": a.id,
                "timestamp": a.timestamp,
                "cycle": a.cycle,
                "business_name": a.business_name,
                "action": a.action,
                "detail": a.detail,
                "impact": a.impact,
                "status": a.status,
                "autonomous": a.autonomous,
            }
            for a in activities
        ],
    }


@router.get("/alerts/{business_id}")
def get_alerts(business_id: str, db: Session = Depends(get_db)):
    """
    Proactive alerts generated by the Organism for a specific business.
    """
    alerts = (
        db.query(OrganismAlert)
        .filter(OrganismAlert.business_id == business_id)
        .order_by(desc(OrganismAlert.timestamp))
        .limit(20)
        .all()
    )
    return {
        "business_id": business_id,
        "unread": sum(1 for a in alerts if not a.read),
        "alerts": [
            {
                "id": a.id,
                "timestamp": a.timestamp,
                "priority": a.priority,
                "title": a.title,
                "body": a.body,
                "action_label": a.action_label,
                "read": a.read,
            }
            for a in alerts
        ],
    }


@router.post("/alerts/{alert_id}/read")
def mark_alert_read(alert_id: int, db: Session = Depends(get_db)):
    """Mark an alert as read."""
    alert = db.query(OrganismAlert).filter(OrganismAlert.id == alert_id).first()
    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found")
    alert.read = True
    db.commit()
    return {"status": "ok"}


@router.get("/stats")
def organism_stats(db: Session = Depends(get_db)):
    """
    High-level Organism impact statistics.
    Shows how much value the Organism has autonomously created.
    """
    total_actions = db.query(OrganismActivity).count()
    cycles_done = (
        db.query(OrganismActivity.cycle, func.count(OrganismActivity.cycle).label("cnt"))
        .group_by(OrganismActivity.cycle)
        .all()
    )
    total_alerts = db.query(OrganismAlert).count()
    unread_alerts = db.query(OrganismAlert).filter(OrganismAlert.read == False).count()
    verifications = (
        db.query(OrganismActivity)
        .filter(OrganismActivity.cycle == "VERIFY")
        .count()
    )
    enrichments = (
        db.query(OrganismActivity)
        .filter(OrganismActivity.cycle == "ENRICH")
        .count()
    )
    last_action = (
        db.query(OrganismActivity)
        .order_by(desc(OrganismActivity.timestamp))
        .first()
    )

    return {
        "total_autonomous_actions": total_actions,
        "total_alerts_generated": total_alerts,
        "unread_alerts": unread_alerts,
        "verifications_run": verifications,
        "profiles_enriched": enrichments,
        "last_action_at": last_action.timestamp if last_action else None,
        "last_action": last_action.action if last_action else "None yet",
        "cycle_breakdown": {c: n for c, n in cycles_done},
    }


from fastapi import BackgroundTasks

@router.post("/trigger")
def trigger_cycle(background_tasks: BackgroundTasks):
    """
    Manually trigger an immediate full Organism cycle.
    Useful for testing or on-demand runs.
    """
    from organism.worker import run_organism_cycle_sync
    background_tasks.add_task(run_organism_cycle_sync)
    return {"status": "triggered", "message": "Organism cycle initiated."}

# ─────────────────────────────────────────────────────────────────────────────
# GHOST PROFILE CLAIMING ENDPOINTS
# ─────────────────────────────────────────────────────────────────────────────

from auth.security import get_password_hash, create_access_token, ACCESS_TOKEN_EXPIRE_MINUTES
from datetime import timedelta
from pydantic import BaseModel
from typing import Optional

class ClaimPayload(BaseModel):
    email: Optional[str] = None
    password: Optional[str] = None
    full_name: Optional[str] = None
    phone: Optional[str] = None

@router.get("/claim/{token}")
def get_ghost_profile(token: str, db: Session = Depends(get_db)):
    """Fetch a ghost profile by its secure token with rich growth metrics."""
    biz = db.query(Business).filter(Business.ghost_token == token, Business.claimed == False).first()
    if not biz:
        # Check if already claimed
        claimed_biz = db.query(Business).filter(Business.ghost_token == token, Business.claimed == True).first()
        if claimed_biz:
            return {
                "id": claimed_biz.id,
                "name": claimed_biz.name,
                "already_claimed": True,
                "message": "This business has already been claimed."
            }
        raise HTTPException(status_code=404, detail="Invalid or expired claim token.")
    
    return {
        "id": biz.id,
        "name": biz.name,
        "category": biz.category,
        "location": biz.location,
        "description": biz.description or f"Leading {biz.category} specialist based in {biz.location}.",
        "source_url": biz.source_url,
        "photo_url": biz.photo_url or "https://images.unsplash.com/photo-1556740758-90de374c12ad?w=800&auto=format&fit=crop&q=60",
        "phone": biz.phone or "+234 800 000 0000",
        "website": biz.website,
        "services": biz.services or ["Core Products", "Custom Consultation", "Express Delivery", "Warranty Service"],
        "rating": biz.rating or 4.9,
        "review_count": biz.review_count or 18,
        "profile_views": max(biz.profile_views or 0, 184),
        "search_appearances": max(biz.search_appearances or 0, 420),
        "estimated_monthly_demand": 310,
        "ai_hook": f"Discover how {biz.name} delivers premier {biz.category.lower()} in {biz.location}. Fast, trusted, and locally verified.",
        "trial_days": 14,
        "already_claimed": False
    }

@router.post("/claim/{token}")
def claim_ghost_profile(
    token: str,
    payload: Optional[ClaimPayload] = None,
    db: Session = Depends(get_db)
):
    """
    Claim a ghost profile. Supports:
    1. Direct 1-click registration with email & password.
    2. Or linking to an existing user record.
    """
    biz = db.query(Business).filter(Business.ghost_token == token, Business.claimed == False).first()
    if not biz:
        raise HTTPException(status_code=404, detail="Invalid or expired claim token.")
    
    user = None
    access_token = None

    if payload and payload.email:
        email = payload.email.strip().lower()
        user = db.query(User).filter(User.email == email).first()
        if not user:
            pwd = payload.password or "DimaDefaultPassword2026!"
            hashed_password = get_password_hash(pwd)
            user = User(
                email=email,
                hashed_password=hashed_password,
                role="business_owner",
                business_id=biz.id
            )
            db.add(user)
            db.commit()
            db.refresh(user)
        else:
            user.business_id = biz.id
            user.role = "business_owner"
            db.commit()

        access_token_expires = timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
        access_token = create_access_token(
            data={"sub": user.email}, expires_delta=access_token_expires
        )
    
    # Mark business as claimed
    biz.claimed = True
    biz.contact_email = payload.email if payload and payload.email else biz.contact_email
    if payload and payload.phone:
        biz.phone = payload.phone
    db.commit()
    
    return {
        "status": "success",
        "message": f"Welcome to Dima, {biz.name}!",
        "business_id": biz.id,
        "business_name": biz.name,
        "access_token": access_token,
        "token_type": "bearer"
    }
